### PR TITLE
Feature/square charts

### PR DESCRIPTION
**Pull request by akerl**
This is my branch based on #40 .

It adjusts some of the bin code, and cleans up the matrix slice.

I'm not sure how I feel about the padding: this cuts the 14 pixels for the labels, but you end up w/ 2 pixels of unbalanced space on the right and bottom edges. Tempted to trim that out

### CODE REVIEW

**Comment by akerl** [comment]
@blerchin what're your thoughts here? Seems like the right thing to do is mod the SVG to be 13 * row_size - 2 and likewise for columns, so that the padding on bottom and right is trimmed

**Comment by blerchin** [comment]
Looks good! I'm all for clipping off 2px on the edges.

**Comment by akerl** [comment]
Awesome, merged. This should work w/ `githubchart -t svg_square -u akerl output.svg` to generate 7x7 SVG grids

**Comment by akerl** [comment]
I've released 2.0.1 of githubchart which includes this change; thank you for submitting it!

**Comment by blerchin** [comment]
Much obliged!

**Pull request merged**
